import express from 'express';
import * as dotenv from 'dotenv';
import { GoogleGenAI } from '@google/genai';

dotenv.config();

const router = express.Router();

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

router.route('/').get((req, res) => {
  res.status(200).json({ message: "Hello from Gemini Image Generation ROUTES" });
});

router.route('/').post(async (req, res) => {
  try {
    const { prompt } = req.body;

    console.log("Received prompt for Gemini:", prompt);

    const response = await ai.models.generateContent({
        model: 'gemini-3.1-flash-image',
        contents: prompt
    });

    const parts = response.candidates?.[0]?.content?.parts || [];
    const imagePart = parts.find(p => p.inlineData);

    if (imagePart) {
        const base64Image = imagePart.inlineData.data;
        res.status(200).json({ photo: base64Image });
    } else {
        throw new Error("No image generated by the model. Check prompt or model availability.");
    }
  } catch (error) {
    console.error("Error generating image:", error);
    // Return the actual error message so the user knows if they hit a quota/billing limit
    res.status(500).json({ message: error.message || "Something went wrong" });
  }
});

export default router;
